### PR TITLE
Changes to `in_browser_session`

### LINKED ISSUE #107: `in_browser_session` doesn't work properly when using `do`
Whenever `in_browser_session` is used with `do` (i.e. `in_browser_session "some_session" do ... end`), functions inside the `do` block will be executed in the current_session, not the specified session. Furthermore,  a `BadFunctionError` is always raised in the end. 

I believe this is because the functions inside the `do` block are evaluated before calling `in_browser_session` and so it receives the result of the `do` block as its parameter instead of the functions themselves.

An example to illustrate:

```sh
iex(1)> use Hound.Helpers
nil
iex(2)> change_session_to("session A") #will be the default session
"b2e814010ed31a312fd850a00b6cf5db"
iex(3)> change_session_to("session B")                             
"dbadb7ea57cf542985530a6169d50804"
iex(4)> Hound.Helpers.Session.current_session_id #currently in session B
"dbadb7ea57cf542985530a6169d50804"
iex(5)> navigate_to("http://elixir-lang.org")
nil
iex(6)> current_url #session B current url should be "http://elixir-lang.org"
"http://elixir-lang.org/"
iex(7)> in_browser_session "session A" do
...(7)>   navigate_to("http://github.com")
...(7)> end
** (BadFunctionError) expected a function, got: [do: nil]
    (hound) lib/hound/helpers/session.ex:44: Hound.Helpers.Session.in_browser_session/2
iex(7)> change_session_to("session A")
"b2e814010ed31a312fd850a00b6cf5db"
iex(8)> current_url # session A url should be http://github.com but will be data;,
"data:,"
iex(9)> change_session_to("session B")                                            
"dbadb7ea57cf542985530a6169d50804"
iex(10)> current_url # session B url should remain http://elixir-lang.org but will be http://github.com instead           
"https://github.com/"
```

I think the best approach is to make `in_browser_session` a macro, so the `do` block isn't evaluated until the session has changed, im willing to work on this and make a PR. 

Otherwise, `in_broswer_session` needs to be used with a function:

```elixir
in_browser_session "other_session", fn -> 
    navigate_to(http:example.com) 
end
```

so the docs should be updated to reflect the proper usage (current example in the docs uses `in_browser_session ... do ... end`)

### LINKED ISSUE #108: session is not preserved after calling `in_browser_session`.
After `in_browser_session` is called, session is always changed to the default session, irregardless of which was the current session before calling `in_browser_session`.

For example, say i have 3 sessions, `A`, `B` and `C` where `A` is the default session. if, while on session `B` i call 

```elixir 
in_browser_session "C", fn -> nil end
``` 
then current session after the call will be `A` instead of `B`.

I think it would be best if current session was preserved, something along the lines of: 
```elixir
def in_browser_session(session_name, func) do
    before_session = current_session_id
    change_session_to(session_name)
    apply(func, [])
    change_to_session(before_session)
  end
```

im willing to work on this and make a PR.

### PR DESCRIPTION
**Pull request by msambarino**
+ Closes #107 by changing the docs to show usage of `in_browser_session` with an anonymous function.
+ Fixes #108 by storing the current session prior to changing sessions in `in_browser_session` and switching back after `func` is applied.

I've tried to conform as much as possible to the coding style, still, i more than welcome any feedback you may have and please let me know if you'd like me to make any changes or if the approach i took is not the best.

Also, feel free to leave this PR open if you'd like me to work on #109 and include it in this PR.

cheers.

### CODE REVIEW

File: lib/hound/session_server.ex [hunk 1]
```diff
@@ -22,6 +22,17 @@ defmodule Hound.SessionServer do
     end
   end
 
+  def current_session_name(pid) do
+    case :ets.lookup(@name, pid) do
+      [{^pid, _ref, session_id, all_sessions}] ->
+        Enum.find_value all_sessions, fn
+          {name, id} when id == session_id -> name
```
Comment (tuvistavie) [inline lib/hound/session_server.ex]: You can pattern match using `{name, ^session_id}`

**Comment by tuvistavie** [comment]
@msambarino Thank you very much for your PR. I added a small comment, but it looks great!
Also, I think you can go ahead and return the value of `func` as you proposed in #109.
Thanks! :smile:

File: lib/hound/session_server.ex (hunk 1 above)
Comment (msambarino) [inline lib/hound/session_server.ex]: You're right! that would be better.

File: lib/hound/session_server.ex [hunk 2]
```diff
@@ -22,6 +22,17 @@ defmodule Hound.SessionServer do
     end
   end
 
+  def current_session_name(pid) do
+    case :ets.lookup(@name, pid) do
+      [{^pid, _ref, session_id, all_sessions}] ->
+        Enum.find_value all_sessions, fn
+          {name, ^session_id} -> name
```
Comment (msambarino) [inline lib/hound/session_server.ex]: It seems this fails to compile in travis (`** (CompileError) lib/hound/session_server.ex:29: unbound variable ^session_id`). I had no problems compiling or testing locally (Elixir 1.2.4) is this something that has changed since 1.0.4?

Comment (tuvistavie) [inline lib/hound/session_server.ex]: Sorry for the false alert, I just checked and it seems that this is only allowed from 1.2: https://github.com/elixir-lang/elixir/blob/v1.2/CHANGELOG.md#v120-2016-01-01

> [Kernel] Allow the pin operator ^ in fn clauses and on the left side of <- in for comprehensions

Sorry for the extra work, but could you revert to the guard please?

Comment (msambarino) [inline lib/hound/session_server.ex]: Sure thing! ;)

**Comment by tuvistavie** [comment]
@msambarino Perfect, thank you very much :smile:

**Comment by msambarino** [comment]
Thank you! feels great contributing to a tool i use. Keep up the awesome work!
